name: number_converter
description: A library to convert decimal numbers into or from another number system.
version: 1.0.0
repository: https://github.com/tvswe/number_converter
homepage: https://tvswe.eu

environment:
  sdk: '>=2.19.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
